HW by Mironchuk Timophey
AufarZakiev/CPP-2019-2020-HW5 pull request #6
Opened 2019-12-28 16:57 UTC by Limberjack

![Screenshot from 2019-12-28 19-01-06](https://user-images.githubusercontent.com/49205377/71546944-0dbfaa80-29ac-11ea-9fa9-e8f7c13378f2.png)

2019-12-28 19:07 UTC, AufarZakiev requested changes
Неплохо, интересная реализация подсчета ID.
Пройдитесь по комментам, особенно в контсрукторе `Counted`. 
Вызов деструктора вообще (а особенно из конструктора) - это сильно "пахнущий" код. Я даже слабо себе представляю, что будет, если `new` выделит память под объект, вызовет конструктор, а в нем вызовется деструктор. Вернется указатель на мусор, скорее всего.

При невозможности создать объект, ООП говорит нам выбрасывать исключение и это нормальный ход, чтобы добиться главного: отсутствия в программе невалидных объектов. Если невалидных объектов нет, то их нельзя передать в функцию, к ним нельзя применить оператор и т.п. - то есть, мы получаем гарантии, которые облегчают нам жизнь. 

Прокомментируйте код раздачи ID, пожалуйста, никак не могу понять логику условных операторов. И потом напишите побольше тестов: с возвращением объекта из функции, передачей его в функцию и т.п.

2019-12-28 19:07 UTC, AufarZakiev commented on Counted.h
> +  int id;
Codestyle не забываем

2019-12-28 19:07 UTC, AufarZakiev commented on Counted.h
> +  Counted& operator=(const Counted& a) = delete;
Конструктор, деструктор, методы копирования вижу
Rule of Five требует еще что-то, да?)

2019-12-28 19:16 UTC, AufarZakiev commented
Кстати, не забудьте достать скриншот документации, которая объясняет, почему вас класс нельзя положить в `std::vector`

2019-12-28 19:49 UTC, Limberjack commented on Counted.h
> +  Counted& operator=(const Counted& a) = delete;
а чем перемещение мешает условию задачи?

2019-12-28 19:58 UTC, AufarZakiev commented on Counted.h
> +  Counted& operator=(const Counted& a) = delete;
Если считаете, что мешает - пометьте эти методы словом `delete`.
Если считаете, что не мешает - реализуйте эти методы сами или пометьте как `default`, чтобы компилятор сам их сгенерил. По умолчанию он их сгенерит ровно такими же, как операторы копирования

2019-12-28 21:31 UTC, Limberjack commented
> ![Screenshot from 2019-12-28 19-01-06](https://user-images.githubusercontent.com/49205377/71546944-0dbfaa80-29ac-11ea-9fa9-e8f7c13378f2.png)



> Кстати, не забудьте достать скриншот документации, которая объясняет, почему вас класс нельзя положить в `std::vector`

![image](https://user-images.githubusercontent.com/49205377/71549673-7de12700-29d2-11ea-9e20-3b9f52e6ee64.png)

2019-12-29 07:17 UTC, AufarZakiev commented
Это документация?

2019-12-30 10:08 UTC, Limberjack commented
> Это документация?

на этом скриншоте показано, что пушбэк добавляет в вектор или копию объекта или переносит его.  копию при моей реализации он сделать не сможет, т.к. я запретил копирование. однако сможет перенести. перенос я переопределил на перенос с удалением, так что будет существовать только один объект с каким-то айдишником.

2019-12-30 10:15 UTC, AufarZakiev commented
> 
> 
> > Это документация?
> 
> на этом скриншоте показано, что пушбэк добавляет в вектор или копию объекта или переносит его. копию при моей реализации он сделать не сможет, т.к. я запретил копирование. однако сможет перенести. перенос я переопределил на перенос с удалением, так что будет существовать только один объект с каким-то айдишником.

Это я понимаю, однако, нужно найти этот же момент в документации. Суть в том, что выбор нужного контейнера - это очень распространеная задача и я должен быть уверен, что вы понимаете, как работать с документацией по С++.

2019-12-30 10:26 UTC, Limberjack commented
> > > Это документация?
> > 
> > 
> > на этом скриншоте показано, что пушбэк добавляет в вектор или копию объекта или переносит его. копию при моей реализации он сделать не сможет, т.к. я запретил копирование. однако сможет перенести. перенос я переопределил на перенос с удалением, так что будет существовать только один объект с каким-то айдишником.
> 
> Это я понимаю, однако, нужно найти этот же момент в документации. Суть в том, что выбор нужного контейнера - это очень распространеная задача и я должен быть уверен, что вы понимаете, как работать с документацией по С++.

2019-12-30 10:38 UTC, AufarZakiev reviewed
Есть некоторые места, которые соверенно точно надо править. 
И мне кажется, что идея с freeIDLIst - это оверкилл для этой задачи, она решается гораздо проще и изящнее. Посмотрите решения других, пожалуйста, они предлагают другое решение и оно не выбрасывает исключений

2019-12-30 10:38 UTC, AufarZakiev commented on Counted.cpp
> +  a.~Counted();
Вызов деструктора кажется логичным, но теперь подумайте, что будет с объектом a? Если это временный объект, то вы вызываете у него деструктор, а потом компилятор сам вызывает деструктор (в конце его времени жизни). Это по стандарту Undefined behavior. Если это не временный объект, а обычный, с примененными на него `std::move()`, то проблема такая же. 

Вызов деструктора - это возможность языка, которая есть, однако, если вам ее приходится использовать, то это чаще всего повод пересмотреть архитектуру кода

2019-12-30 10:42 UTC, Limberjack commented
![image](https://user-images.githubusercontent.com/49205377/71578688-38c01080-2b0a-11ea-8d98-48a7340c9901.png)

2019-12-30 15:50 UTC, Limberjack commented on Counted.cpp
> +  a.~Counted();
> Есть некоторые места, которые соверенно точно надо править.
> И мне кажется, что идея с freeIDLIst - это оверкилл для этой задачи, она решается гораздо проще и изящнее. Посмотрите решения других, пожалуйста, они предлагают другое решение и оно не выбрасывает исключений

я не увидел у других способа избежания переполнения инта, хранящего последний айдишник

2019-12-30 17:17 UTC, AufarZakiev commented on Counted.cpp
> +  a.~Counted();
> 
> 
> > Есть некоторые места, которые соверенно точно надо править.
> > И мне кажется, что идея с freeIDLIst - это оверкилл для этой задачи, она решается гораздо проще и изящнее. Посмотрите решения других, пожалуйста, они предлагают другое решение и оно не выбрасывает исключений
> 
> я не увидел у других способа избежания переполнения инта, хранящего последний айдишник

Справедливо, стоит мне добавить в задание, что ID точно помещается в какой-то диапазон. Как "достаточно хорошее решение" можно использовать `size_t`, т.к. после него уже только строку с числом хранить придется. Однако, например, `size()` у `std::vector` возвращает именно его - кажется, для практических задач этого хватит за глаза

2019-12-30 17:41 UTC, Limberjack commented on Counted.cpp
> +  a.~Counted();
в условии задачи написано, что у каунтедов должно быть минимальное возможное значение айди, чтобы не создавать объекты с невалидным (переполненым) айдишником

2019-12-30 17:54 UTC, AufarZakiev commented on Counted.cpp
> +  a.~Counted();
Это к чему?
Минимально возможное - все верно. Я говорю, что считайте, что в `int` оно точно поместится. Если хочется перфекционизма - используйте `size_t`. Вся соль задания в реализации минимально возможного.

2020-05-21 15:01 UTC, AufarZakiev requested changes
Никаких изменений по коментам, верно понимаю?

2020-05-21 15:09 UTC, Limberjack commented
> Никаких изменений по коментам, верно понимаю?

я 4 таск добавил. сейчас еще раз посмотрю, что там было

2020-05-25 09:06 UTC, AufarZakiev requested changes
Не понимаю: вижу файл .autosave, в котором что-то есть новое, но в самом файле Counted.cpp все без изменений

2020-05-25 10:20 UTC, Limberjack commented
> Не понимаю: вижу файл .autosave, в котором что-то есть новое, но в самом файле Counted.cpp все без изменений

как сумасшедший параноик на каждом файле раза 4 нажал ctrl+s перед коммитом, чтобы не случилось что-нибудь такое. а оно и случилось

2020-05-25 12:18 UTC, AufarZakiev commented
> 
> 
> > Не понимаю: вижу файл .autosave, в котором что-то есть новое, но в самом файле Counted.cpp все без изменений
> 
> как сумасшедший параноик на каждом файле раза 4 нажал ctrl+s перед коммитом, чтобы не случилось что-нибудь такое. а оно и случилось. хотя странно. я запускал, чтобы проверить работоспособность. qt сохранил код

Разберись плиз

2020-05-25 12:38 UTC, Limberjack commented
> > > Не понимаю: вижу файл .autosave, в котором что-то есть новое, но в самом файле Counted.cpp все без изменений
> > 
> > 
> > как сумасшедший параноик на каждом файле раза 4 нажал ctrl+s перед коммитом, чтобы не случилось что-нибудь такое. а оно и случилось. хотя странно. я запускал, чтобы проверить работоспособность. qt сохранил код
> 
> Разберись плиз

поправил

2020-05-25 12:44 UTC, AufarZakiev commented
Request review?

2020-05-25 13:32 UTC, AufarZakiev approved these changes

2022-05-18 21:21 UTC, closed without merging